/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.dapoerberkahbandung.view;

/**
 *
 * @author Dandi Ahmadin
 */
public class BerandaView extends javax.swing.JPanel {

    /**
     * Creates new form BerandaView
     */
    public BerandaView() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Judul = new javax.swing.JLabel();
        saldoPanel = new javax.swing.JPanel();
        saldo = new javax.swing.JLabel();
        pemasukanPanel = new javax.swing.JPanel();
        pemasukan = new javax.swing.JLabel();
        pengeluaranPanel = new javax.swing.JPanel();
        pengeluaran = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 245, 224));
        setPreferredSize(new java.awt.Dimension(600, 480));

        Judul.setFont(new java.awt.Font("Century Gothic", 1, 26)); // NOI18N
        Judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul.setText("Selamat Datang, Admin.");

        saldoPanel.setBackground(new java.awt.Color(255, 255, 255));

        saldo.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        saldo.setText("Saldo");

        javax.swing.GroupLayout saldoPanelLayout = new javax.swing.GroupLayout(saldoPanel);
        saldoPanel.setLayout(saldoPanelLayout);
        saldoPanelLayout.setHorizontalGroup(
            saldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saldoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saldo)
                .addContainerGap(426, Short.MAX_VALUE))
        );
        saldoPanelLayout.setVerticalGroup(
            saldoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saldoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saldo)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pemasukanPanel.setBackground(new java.awt.Color(255, 255, 255));
        pemasukanPanel.setPreferredSize(new java.awt.Dimension(230, 100));

        pemasukan.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        pemasukan.setText("Pemasukan");

        javax.swing.GroupLayout pemasukanPanelLayout = new javax.swing.GroupLayout(pemasukanPanel);
        pemasukanPanel.setLayout(pemasukanPanelLayout);
        pemasukanPanelLayout.setHorizontalGroup(
            pemasukanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemasukanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pemasukan)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        pemasukanPanelLayout.setVerticalGroup(
            pemasukanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemasukanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pemasukan)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pengeluaranPanel.setBackground(new java.awt.Color(255, 255, 255));

        pengeluaran.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        pengeluaran.setText("Pengeluaran");

        javax.swing.GroupLayout pengeluaranPanelLayout = new javax.swing.GroupLayout(pengeluaranPanel);
        pengeluaranPanel.setLayout(pengeluaranPanelLayout);
        pengeluaranPanelLayout.setHorizontalGroup(
            pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pengeluaran)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        pengeluaranPanelLayout.setVerticalGroup(
            pengeluaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengeluaranPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pengeluaran)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pemasukanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pengeluaranPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(saldoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Judul)
                .addGap(103, 103, 103)
                .addComponent(saldoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pengeluaranPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pemasukanPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel pemasukan;
    private javax.swing.JPanel pemasukanPanel;
    private javax.swing.JLabel pengeluaran;
    private javax.swing.JPanel pengeluaranPanel;
    private javax.swing.JLabel saldo;
    private javax.swing.JPanel saldoPanel;
    // End of variables declaration//GEN-END:variables
}
