/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.dapoerberkahbandung.view;

import com.toedter.calendar.JDateChooser;
import id.dapoerberkahbandung.controller.PemasukanController;
import id.dapoerberkahbandung.database.Koneksi;
import id.dapoerberkahbandung.entity.Anggota;
import id.dapoerberkahbandung.entity.Donatur;
import id.dapoerberkahbandung.entity.Pemasukan;
import id.dapoerberkahbandung.error.AnggotaException;
import id.dapoerberkahbandung.error.DonaturException;
import id.dapoerberkahbandung.error.PemasukanException;
import id.dapoerberkahbandung.event.PemasukanListener;
import id.dapoerberkahbandung.model.PemasukanModel;
import id.dapoerberkahbandung.model.TabelPemasukanModel;
import id.dapoerberkahbandung.service.PemasukanDao;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Dandi Ahmadin
 */
public class PemasukanView extends javax.swing.JPanel implements PemasukanListener, ListSelectionListener{

    /**
     * Creates new form PemasukanView
     */
    
    private TabelPemasukanModel tabelPemasukanModel;
    private PemasukanModel model;
    private PemasukanController controller;
    
    public PemasukanView() throws PemasukanException {
        initComponents();
        tabelPemasukanModel = new TabelPemasukanModel();
        model = new PemasukanModel();
        controller = new PemasukanController();
        
        
        
        model.setListener(this);
        controller.setModel(model);
        tabelPemasukan.getSelectionModel().addListSelectionListener(this);
        tabelPemasukan.setModel(tabelPemasukanModel);
        
        model.resetPemasukan();
    }

    public JDateChooser getDateChooser() {
        return dateChooser;
    }
    public JComboBox<String> getComboBoxAnggota() {
        return comboBoxAnggota;
    }
    
    public JComboBox<String> getComboBoxDonatur() {
        return comboBoxDonatur;
    }
    
    public JTable getTabelPemasukan() {
        return tabelPemasukan;
    }

    public JTextField getTxtNoPemasukan() {
        return txtNoPemasukan;
    }

    public JTextField getTxtRekening() {
        return txtRekening;
    }

    public JTextField getTxtUangTunai() {
        return txtUangTunai;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        dataPemasukan = new javax.swing.JLabel();
        no_pemasukan = new javax.swing.JLabel();
        anggota = new javax.swing.JLabel();
        donatur = new javax.swing.JLabel();
        rekening = new javax.swing.JLabel();
        uangTunai = new javax.swing.JLabel();
        txtNoPemasukan = new javax.swing.JTextField();
        comboBoxAnggota = new javax.swing.JComboBox<>();
        comboBoxDonatur = new javax.swing.JComboBox<>();
        txtRekening = new javax.swing.JTextField();
        txtUangTunai = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPemasukan = new javax.swing.JTable();
        dateChooser = new com.toedter.calendar.JDateChooser();
        anggota1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(250, 245, 224));
        setPreferredSize(new java.awt.Dimension(600, 480));

        dataPemasukan.setFont(new java.awt.Font("Century Gothic", 1, 26)); // NOI18N
        dataPemasukan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dataPemasukan.setText("Data Pemasukan");

        no_pemasukan.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        no_pemasukan.setText("Nomor Pemasukan :");

        anggota.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        anggota.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        anggota.setText("Nama Anggota :");

        donatur.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        donatur.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        donatur.setText("Nama Donatur :");

        rekening.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        rekening.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rekening.setText("Rekening :");

        uangTunai.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        uangTunai.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uangTunai.setText("Uang Tunai :");

        txtNoPemasukan.setEditable(false);
        txtNoPemasukan.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtNoPemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoPemasukanActionPerformed(evt);
            }
        });

        comboBoxAnggota.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        comboBoxAnggota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBoxDonatur.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        comboBoxDonatur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtRekening.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        txtUangTunai.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        btnReset.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnTambah.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tabelPemasukan.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tabelPemasukan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(tabelPemasukan);

        dateChooser.setDateFormatString("dd MMMM yyyy");
        dateChooser.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        dateChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateChooserPropertyChange(evt);
            }
        });

        anggota1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        anggota1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        anggota1.setText("Tanggal :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dataPemasukan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(no_pemasukan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(anggota1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNoPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(btnReset)
                                .addGap(18, 18, 18)
                                .addComponent(btnTambah)
                                .addGap(18, 18, 18)
                                .addComponent(btnUbah)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rekening, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(donatur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(anggota, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(uangTunai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(comboBoxDonatur, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRekening, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUangTunai, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 75, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(dataPemasukan)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no_pemasukan)
                    .addComponent(txtNoPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(anggota1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anggota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxDonatur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(donatur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRekening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rekening))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUangTunai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uangTunai))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoPemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoPemasukanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoPemasukanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        controller.resetPemasukan(this);
        comboBoxAnggota.setSelectedIndex(0);
        comboBoxDonatur.setSelectedIndex(0);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        controller.insertPemasukan(this);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        controller.updatePemasukan(this);
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        controller.deletePemasukan(this);
    }//GEN-LAST:event_btnHapusActionPerformed

    private void dateChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChooserPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dateChooserPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anggota;
    private javax.swing.JLabel anggota1;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> comboBoxAnggota;
    private javax.swing.JComboBox<String> comboBoxDonatur;
    private javax.swing.JLabel dataPemasukan;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel donatur;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel no_pemasukan;
    private javax.swing.JLabel rekening;
    private javax.swing.JTable tabelPemasukan;
    private javax.swing.JTextField txtNoPemasukan;
    private javax.swing.JTextField txtRekening;
    private javax.swing.JTextField txtUangTunai;
    private javax.swing.JLabel uangTunai;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(PemasukanModel model) {
        txtNoPemasukan.setText(model.getNo_pemasukan() + "");
        dateChooser.setDate(model.getTanggal());
        comboBoxAnggota.setSelectedItem(model.getId_anggota());
        comboBoxDonatur.setSelectedItem(model.getId_donatur());
        txtRekening.setText(String.valueOf(model.getRekening()));
        txtUangTunai.setText(String.valueOf(model.getUang_tunai()));
    }

    @Override
    public void onInsert(Pemasukan pemasukan) {
        tabelPemasukanModel.add(pemasukan);
        try {
            loadDatabase();
        } catch (SQLException | PemasukanException | AnggotaException | DonaturException ex) {
            Logger.getLogger(PemasukanView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void onUpdate(Pemasukan pemasukan) {
        int index = tabelPemasukan.getSelectedRow();
        tabelPemasukanModel.set(index, pemasukan);
        try {
            loadDatabase();
        } catch (SQLException | PemasukanException | AnggotaException | DonaturException ex) {
            Logger.getLogger(PemasukanView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void onDelete() {
        int index = tabelPemasukan.getSelectedRow();
        tabelPemasukanModel.remove(index);
        try {
            loadDatabase();
        } catch (SQLException | PemasukanException | AnggotaException | DonaturException ex) {
            Logger.getLogger(PemasukanView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void valueChanged(ListSelectionEvent lse) {
        try {
            Pemasukan model = tabelPemasukanModel.get(tabelPemasukan.getSelectedRow());
            txtNoPemasukan.setText(model.getNo_pemasukan() + "");
            dateChooser.setDate(model.getTanggal());
            comboBoxAnggota.setSelectedItem(model.getId_anggota());
            comboBoxDonatur.setSelectedItem(model.getId_donatur());
            txtRekening.setText(model.getRekening() + "");
            txtUangTunai.setText(model.getUang_tunai() + "");
        } catch (IndexOutOfBoundsException exception) {
        }
    }
    
    public void loadDatabase() throws SQLException, PemasukanException, AnggotaException, DonaturException {
        PemasukanDao dao = Koneksi.getPemasukanDao();
        tabelPemasukanModel.setList(dao.selectAllPemasukan());
        comboBoxAnggota.removeAllItems();
        comboBoxDonatur.removeAllItems();
        
        comboBoxAnggota.addItem("~ Pilih ~");
        comboBoxDonatur.addItem("~ Pilih ~");
        
        List<Anggota> id_anggota = dao.selectNameAnggota();
        for (Anggota id : id_anggota) {
            comboBoxAnggota.addItem(String.valueOf(id.getNama()));
        }
        
        List<Donatur> id_donatur = dao.selectNameDonatur();
        for (Donatur id : id_donatur) {
            comboBoxDonatur.addItem(String.valueOf(id.getNama()));
        }
    }
}
